$ErrorActionPreference = "Stop"
$repo = Split-Path -Parent $PSScriptRoot
$envPath = Join-Path $repo "apps\dashboard\.env.local"

if (Test-Path $envPath) {
  Write-Host "Already exists: $envPath"
  Write-Host "Preserving it. Review or edit it before starting UIOS."
  exit 0
}

$bytes = New-Object byte[] 32
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$rng.GetBytes($bytes)
$rng.Dispose()
$secret = [Convert]::ToBase64String($bytes).Replace('+','-').Replace('/','_').TrimEnd('=')

@"
# Generated by scripts/setup-local.ps1. This file is ignored by git.
UIOS_WORKSPACE_SECRET=$secret
UIOS_STATE_DB=.uios-data/uios.sqlite
UIOS_AUDIT_RETENTION_DAYS=365
UIOS_ROUTING_STRATEGY=explicit
UIOS_AEGIS_REQUIRED=false
UIOS_AEGIS_FAIL_CLOSED=true

# Add your provider credentials to enable live model responses.
UIOS_AI_GATEWAY_URL=https://ai-gateway.vercel.sh/v1/chat/completions
UIOS_AI_GATEWAY_KEY=
UIOS_DEFAULT_MODEL=
"@ | Set-Content -LiteralPath $envPath -Encoding utf8

Write-Host "Created $envPath"
Write-Host "Next: add UIOS_AI_GATEWAY_KEY and UIOS_DEFAULT_MODEL, then run: corepack pnpm dev"
