"use client";
import { useEffect, useState } from "react";

type Key = { id: string; name: string; role: string; keyPrefix: string; createdAt: string; lastUsedAt?: string; revokedAt?: string };
export function ApiKeyConsole() {
  const [keys, setKeys] = useState<Key[]>([]); const [name, setName] = useState(""); const [raw, setRaw] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/keys", { cache: "no-store" }); if (response.ok) setKeys((await response.json()).keys ?? []); }
  useEffect(() => { load().catch(() => undefined); }, []);
  async function create() { if (!name.trim()) return; setBusy(true); setMessage(""); try { const response = await fetch("/api/keys", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setRaw(body.rawKey); setName(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not create key."); } finally { setBusy(false); } }
  async function revoke(id: string) { setBusy(true); try { await fetch(`/api/keys?id=${encodeURIComponent(id)}`, { method: "DELETE" }); await load(); } finally { setBusy(false); } }
  return <section className="key-console" aria-label="API key management"><div className="key-console-head"><div><div className="panel-kicker">Developer access</div><h2>Keys that stay under your control.</h2><p>Create scoped workspace credentials. UIOS stores only hashes; raw keys appear once.</p></div><div className="key-create"><input aria-label="Key name" value={name} onChange={(event) => setName(event.target.value)} placeholder="production-router" maxLength={80} /><button className="button" onClick={create} disabled={busy || !name.trim()}>Create key</button></div></div>{raw ? <div className="key-secret"><strong>Copy this key now</strong><code>{raw}</code><button onClick={() => navigator.clipboard?.writeText(raw)}>Copy</button><button onClick={() => setRaw("")} aria-label="Dismiss">×</button></div> : null}{message ? <p className="key-error">{message}</p> : null}<div className="key-list">{keys.length ? keys.map((key) => <div className="key-row" key={key.id}><span className="key-status" /><div><strong>{key.name}</strong><small>{key.role} · {key.keyPrefix}… · created {new Date(key.createdAt).toLocaleDateString()}</small></div><button className="quiet-button" disabled={busy || Boolean(key.revokedAt)} onClick={() => revoke(key.id)}>{key.revokedAt ? "Revoked" : "Revoke"}</button></div>) : <span className="key-empty">No workspace keys yet.</span>}</div></section>;
}
